pipeline {
    agent any

    environment {
        DOCKER_HUB_REPO = 'nandesh25/practice-11'
        IMAGE_TAG = "latest"
    }

    stages {
        stage('Clone Repository') {
            steps {
                git url: 'https://github.com/Universe7Nandu/practice-11.git', branch: 'main'
            }
        }

        stage('Build Java Application') {
            steps {
                dir('practice-11') {
                    sh 'mvn clean package'
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                script {
                    sh "docker build -t nandesh25/practice-11:latest -f practice-11/Dockerfile ."
                }
            }
        }

        stage('Login to Docker Hub') {
            steps {
                script {
                    withCredentials([usernamePassword(credentialsId: 'dockerhub-credentials', usernameVariable: 'nandesh25', passwordVariable: 'Nirmala@123.')]) {
                        sh "echo Nirmala@123. | docker login -u nandesh25 --password-stdin"
                    }
                }
            }
        }

        stage('Push Docker Image') {
            steps {
                script {
                    sh "docker push nandesh25/practice-11:latest"
                }
            }
        }
    }

    post {
        always {
            script {
                sh 'docker rmi nandesh25/practice-11:latest || true'
            }
        }
    }
}
